
export interface StakingPosition {
  id: string;
  amount: number;
  originalTokenAmount: number;
  currentValue: number;
  earnedAmount: number;
  
  // New APY-based fields
  desiredAPY: number; // User's desired APY (e.g., 0.15 for 15%)
  riskScore: number; // 0-10000 based on formula
  payoutPriority: number; // 10000 - riskScore
  baseAPY: number; // Risk-free rate (T-Bills, e.g., 0.05)
  maxAPY: number; // Maximum possible APY in the pool
  
  // Legacy fields for backwards compatibility
  riskLevel: number; // Will be calculated from riskScore
  riskCategory: 'Conservative' | 'Moderate' | 'Aggressive';
  apy: number; // Will be same as desiredAPY
  
  createdAt: Date;
  nextPayoutDate: Date; // дата следующей выплаты
  payoutFrequency: number; // частота выплат в днях (7 для еженедельных)
  status: 'active' | 'withdrawn';
  
  // New tracking fields
  missedPayouts: number; // Amount not received due to low priority
  actualAPY: number; // Actual received APY vs desired
}

export interface TokenBalance {
  symbol: string;
  balance: number;
  usdValue: number;
  change?: string;
}

export interface PoolSettings {
  baseAPY: number; // Risk-free rate (T-Bills)
  maxAPY: number; // Maximum possible APY
  lambda: number; // Risk sensitivity coefficient
  totalPoolValue: number; // Total value in the pool
  dailyYield: number; // Daily yield generated by the pool
}
