// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlwglyqjbjlvtqbizlzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsd2dseXFqYmpsdnRxYml6bHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzA2NDYsImV4cCI6MjA2ODk0NjY0Nn0.zli3yvvQaEnPsyFww9X0uFj5eOF7IC185g5tPJgdJ1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});